spring:
  profiles:
#表示所用配置文件为application-dev.yml
  active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jufan_cash_loan?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapperLocations: classpath*:mapper/*.xml