spring:
  profiles:
#表示所用配置文件为application-dev.yml
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  thymeleaf:
    cache: false

mybatis:
  mapperLocations: classpath*:xml/*.xml